import React, { useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import '../styles/Login.css'; // Reusing base styles

const SignUp = () => {
  const [formData, setFormData] = useState({
    companyName: '',
    fullName: '',
    email: '',
    phone: ''
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(null);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSignUp = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess(null);

    try {
      const response = await axios.post('http://localhost:5000/api/auth/signup', formData);
      setSuccess({
        employeeCode: response.data.employeeCode,
        initialPassword: response.data.initialPassword
      });
    } catch (err) {
      setError(err.response?.data?.message || 'Error creating account');
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card signup-card">
        <h1 className="app-title">Human Resource Management System</h1>
        
        <div className="logo-upload">
          <div className="logo-box dashed">
             <span role="img" aria-label="logo">🏢</span>
             <p>App/Web Logo</p>
          </div>
          <button className="upload-link">← Upload Logo</button>
        </div>

        <form onSubmit={handleSignUp} className="auth-form">
          <div className="form-grid">
            <div className="form-group flex">
              <label>Company Name :-</label>
              <input type="text" name="companyName" placeholder="Enter company name" onChange={handleChange} required />
            </div>

            <div className="form-group flex">
              <label>Name :-</label>
              <input type="text" name="fullName" placeholder="Full Name" onChange={handleChange} required />
            </div>

            <div className="form-group flex">
              <label>Email :-</label>
              <input type="email" name="email" placeholder="admin@company.com" onChange={handleChange} required />
            </div>

            <div className="form-group flex">
              <label>Phone :-</label>
              <input type="text" name="phone" placeholder="+1 (555) 000-0000" onChange={handleChange} required />
            </div>
            
            <div className="info-box">
              <p>ℹ️ Password will be auto-generated by the system.</p>
            </div>
          </div>

          {error && <p className="error-message">{error}</p>}
          
          {success && (
            <div className="success-box">
              <p>✅ Employee Created Successfully!</p>
              <p><strong>Login ID:</strong> {success.employeeCode}</p>
              <p><strong>Initial Password:</strong> {success.initialPassword}</p>
              <p className="tiny">Please share these credentials with the employee.</p>
            </div>
          )}

          <button type="submit" className="auth-btn">SIGN UP</button>
        </form>

        <p className="auth-footer">
          Already have an account? <Link to="/login">Sign In</Link>
        </p>
      </div>
    </div>
  );
};

export default SignUp;
